import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pieczara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Oswald:wght@700&display=swap"
          rel="stylesheet"
        />
      </Head>

      {/* todo component */}
      {/* <div>
        <video
          // poster="/main_poster_vid.webp"
          autoPlay
          muted
          loop
        >
          <source src="/main_vid.mp4" />
        </video>
      </div> */}
    </div>
  );
}
