import Head from "next/head";

import TopHeader from "../components/TopHeader";
import Navigation from "../components/Navigation";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pieczara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopHeader />
      <Navigation />

      {/* todo component */}
      {/* <div>
        <video
          // poster="/main_poster_vid.webp"
          //  autoPlay
          muted
          loop
        >
          <source src="/main_vid.mp4" />
        </video>
      </div> */}
    </div>
  );
}
